server:
  port: 8081


spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/fwdb?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver


